global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: "railway-prom"

rule_files:
  - "recording_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: :"node"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "ponder-prod"
    static_configs:
      - targets:  ["prysmindexer-production.up.railway.app"] #["*.up.railway.app"] is the generic format,  the ponder should also likely gave /metrics subpath defined

  - job_name: "ponder-dev"
    static_configs:
      - targets: ["prysmindexer-production.up.railway.app"] #["*.up.railway.app"] is the generic format,  the ponder should also likely gave /metrics subpath defined

  # IF you wanna add postgres monitoring
  # - job_name: 'postgres'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9187']
